using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CopilotApiProject.Models;

/// <summary>
/// Represents a user entity in the TechHive User Management System.
/// This model contains all the essential information about an employee
/// including personal details, employment information, and system metadata.
/// </summary>
public class User
{
    /// <summary>
    /// Gets or sets the unique identifier for the user.
    /// This is the primary key and is auto-generated by the database.
    /// </summary>
    [Key]
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the user's first name.
    /// Required field with minimum length of 2 characters and maximum of 50.
    /// </summary>
    [Required]
    [StringLength(50, MinimumLength = 2)]
    public string FirstName { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the user's last name.
    /// Required field with minimum length of 2 characters and maximum of 50.
    /// </summary>
    [Required]
    [StringLength(50, MinimumLength = 2)]
    public string LastName { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the user's email address.
    /// Must be a valid email format and unique across all users.
    /// Required field with maximum length of 100 characters.
    /// </summary>
    [Required]
    [EmailAddress]
    [StringLength(100)]
    public string Email { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the user's phone number.
    /// Optional field with maximum length of 15 characters.
    /// Can include country codes and formatting.
    /// </summary>
    [StringLength(15)]
    public string? PhoneNumber { get; set; }

    /// <summary>
    /// Gets or sets the department where the user works.
    /// Required field (e.g., "IT", "HR", "Marketing", "Finance").
    /// Maximum length of 50 characters.
    /// </summary>
    [Required]
    [StringLength(50)]
    public string Department { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the user's job position/title.
    /// Required field (e.g., "Software Developer", "HR Manager").
    /// Maximum length of 100 characters.
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Position { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the date and time when the user record was created.
    /// Automatically set to UTC time when the user is first created.
    /// Uses datetime2 SQL type for better precision.
    /// </summary>
    [Column(TypeName = "datetime2")]
    public DateTime CreatedDate { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Gets or sets the date and time when the user record was last updated.
    /// Null when the record has never been updated.
    /// Automatically set to UTC time when any update occurs.
    /// </summary>
    [Column(TypeName = "datetime2")]
    public DateTime? UpdatedDate { get; set; }

    /// <summary>
    /// Gets or sets whether the user account is active.
    /// Defaults to true for new users.
    /// Used for soft deletion - when set to false, the user is considered deleted
    /// but the record is preserved for audit purposes.
    /// </summary>
    public bool IsActive { get; set; } = true;

    /// <summary>
    /// Gets or sets the user's physical address.
    /// Optional field for contact information.
    /// Maximum length of 200 characters.
    /// </summary>
    [StringLength(200)]
    public string? Address { get; set; }

    /// <summary>
    /// Gets or sets the user's salary amount.
    /// Optional field stored as decimal with 18 digits total and 2 decimal places.
    /// Can be null if salary information is confidential or not applicable.
    /// </summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal? Salary { get; set; }

    /// <summary>
    /// Gets or sets the date when the user was hired by the company.
    /// Optional field that can be null for contractors or temporary employees.
    /// </summary>
    public DateTime? HireDate { get; set; }

    /// <summary>
    /// Gets the user's full name by combining first and last names.
    /// This is a computed property and is not stored in the database.
    /// Used for display purposes and search functionality.
    /// </summary>
    [NotMapped]
    public string FullName => $"{FirstName} {LastName}";
}